### ISSUE TITLE
Auto Refresh only works on original website

### ISSUE THREAD

**Issue by mountainash** [clickontyler/VirtualHostX-Issues#90]
It seems that the Auto Refresh feature will only work on the original ("first created") website created with Virtual HostX.

I've created extra sites to test this and with various Local Paths and come to this conclusion. Also the WebSocket port never changes (for each site), which could be a problem when you have multiple enabled sites at once (unless your ws:// server is looking at the referral?)

Version 8.6.0
System Version: 10.14.3

Monitoring code:
`	<script type="text/javascript">
		var connection = new WebSocket('ws://localhost:62183');
		connection.onopen = function (e) {
			console.log('socket open');
		};
		connection.onmessage = function (e) {
			console.log('message event received!');
		};
		connection.onerror = function (e) {
			console.log('error event received!');

//			location.reload();
		};
	</script>`

**Comment by tylerhall** [comment]
So, I definitely found a bug in my websocket server library that was preventing ANY ws:// connections from begin established in Firefox. I've fixed that.

But I can't reproduce what you're describing.

I just tested three different websites in VHX. Each has a different local path. With three browser windows open, I was able to edit and save changes to any of the websites in any order/combination and their corresponding browser window would reload.

When you say

> will only work on the original ("first created") website created 

do you mean the first website to make a connection back to VHX? i.e. the first website you load in a browser? Or do you mean the first website you actually created inside the VHX app itself? Something else?

**Comment by mountainash** [comment]
I mean the first website created in VHX. All subsequent ones don't get a WS reply/or error. Even changing the path on the secondary ones to the same path at the original, with the original disabled doesn't fix it.

Changing the path on the original to other sites DOES work. 

I even created brand new sites. They didn't work. Only the original.
